gText_HowLongToWait::
	.string "It is currently {COLOR RED}{STR_VAR_2}{COLOR DARK_GREY}).\n"
	.string "How long would you like to wait?$"
	
gText_YouCantWaitNow::
	.string "You can't wait right now.$"
	
gText_WaitingTooOften::
	.string "You've waited for too long! Keep going\n"
	.string "to recharge your wait time.$"

gText_HoursRemaining::
	.string "TIME LEFT:\n"
	.string "{COLOR RED}{STR_VAR_2}$"
	
gText_Hour::
	.string "HOUR$"
	
gText_S::
	.string "S$"
	
gText_NotEnoughTime::
	.string "You can't wait for that long. Would you\n"
	.string "like to wait for as long as possible?$"
