	.align 1
gMetatiles_General::
	.incbin "data/tilesets/primary/general/metatiles.bin"

	.align 1
gMetatileAttributes_General::
	.incbin "data/tilesets/primary/general/metatile_attributes.bin"

	.align 1
gMetatileAttributes2_General::
	.incbin "data/tilesets/primary/general/metatile_attributes_2.bin"

	.align 1
gMetatileMaterialTop_General::
	.incbin "data/tilesets/primary/general/metatile_material_top.bin"

	.align 1
gMetatileMaterialBottom_General::
	.incbin "data/tilesets/primary/general/metatile_material_bottom.bin"

	.align 1
gMetatiles_Petalburg::
	.incbin "data/tilesets/secondary/petalburg/metatiles.bin"

	.align 1
gMetatileAttributes_Petalburg::
	.incbin "data/tilesets/secondary/petalburg/metatile_attributes.bin"

	.align 1
gMetatileAttributes2_Petalburg::
	.incbin "data/tilesets/secondary/petalburg/metatile_attributes_2.bin"

	.align 1
gMetatileMaterialTop_Petalburg::
	.incbin "data/tilesets/secondary/petalburg/metatile_material_top.bin"

	.align 1
gMetatileMaterialBottom_Petalburg::
	.incbin "data/tilesets/secondary/petalburg/metatile_material_bottom.bin"

	.align 1
gMetatiles_Rustboro::
	.incbin "data/tilesets/secondary/rustboro/metatiles.bin"

	.align 1
gMetatileAttributes_Rustboro::
	.incbin "data/tilesets/secondary/rustboro/metatile_attributes.bin"

	.align 1
gMetatileAttributes2_Rustboro::
	.incbin "data/tilesets/secondary/rustboro/metatile_attributes_2.bin"

	.align 1
gMetatileMaterialTop_Rustboro::
	.incbin "data/tilesets/secondary/rustboro/metatile_material_top.bin"

	.align 1
gMetatileMaterialBottom_Rustboro::
	.incbin "data/tilesets/secondary/rustboro/metatile_material_bottom.bin"

	.align 1
gMetatiles_Dewford::
	.incbin "data/tilesets/secondary/dewford/metatiles.bin"

	.align 1
gMetatileAttributes_Dewford::
	.incbin "data/tilesets/secondary/dewford/metatile_attributes.bin"

	.align 1
gMetatileAttributes2_Dewford::
	.incbin "data/tilesets/secondary/dewford/metatile_attributes_2.bin"

	.align 1
gMetatileMaterialTop_Dewford::
	.incbin "data/tilesets/secondary/dewford/metatile_material_top.bin"

	.align 1
gMetatileMaterialBottom_Dewford::
	.incbin "data/tilesets/secondary/dewford/metatile_material_bottom.bin"

	.align 1
gMetatiles_Slateport::
	.incbin "data/tilesets/secondary/slateport/metatiles.bin"

	.align 1
gMetatileAttributes_Slateport::
	.incbin "data/tilesets/secondary/slateport/metatile_attributes.bin"

	.align 1
gMetatileAttributes2_Slateport::
	.incbin "data/tilesets/secondary/slateport/metatile_attributes_2.bin"

	.align 1
gMetatileMaterialTop_Slateport::
	.incbin "data/tilesets/secondary/slateport/metatile_material_top.bin"

	.align 1
gMetatileMaterialBottom_Slateport::
	.incbin "data/tilesets/secondary/slateport/metatile_material_bottom.bin"

	.align 1
gMetatiles_Mauville::
	.incbin "data/tilesets/secondary/mauville/metatiles.bin"

	.align 1
gMetatileAttributes_Mauville::
	.incbin "data/tilesets/secondary/mauville/metatile_attributes.bin"

	.align 1
gMetatileAttributes2_Mauville::
	.incbin "data/tilesets/secondary/mauville/metatile_attributes_2.bin"

	.align 1
gMetatileMaterialTop_Mauville::
	.incbin "data/tilesets/secondary/mauville/metatile_material_top.bin"

	.align 1
gMetatileMaterialBottom_Mauville::
	.incbin "data/tilesets/secondary/mauville/metatile_material_bottom.bin"

	.align 1
gMetatiles_Lavaridge::
	.incbin "data/tilesets/secondary/lavaridge/metatiles.bin"

	.align 1
gMetatileAttributes_Lavaridge::
	.incbin "data/tilesets/secondary/lavaridge/metatile_attributes.bin"

	.align 1
gMetatileAttributes2_Lavaridge::
	.incbin "data/tilesets/secondary/lavaridge/metatile_attributes_2.bin"

	.align 1
gMetatileMaterialTop_Lavaridge::
	.incbin "data/tilesets/secondary/lavaridge/metatile_material_top.bin"

	.align 1
gMetatileMaterialBottom_Lavaridge::
	.incbin "data/tilesets/secondary/lavaridge/metatile_material_bottom.bin"

	.align 1
gMetatiles_Fallarbor::
	.incbin "data/tilesets/secondary/fallarbor/metatiles.bin"

	.align 1
gMetatileAttributes_Fallarbor::
	.incbin "data/tilesets/secondary/fallarbor/metatile_attributes.bin"

	.align 1
gMetatileAttributes2_Fallarbor::
	.incbin "data/tilesets/secondary/fallarbor/metatile_attributes_2.bin"

	.align 1
gMetatileMaterialTop_Fallarbor::
	.incbin "data/tilesets/secondary/fallarbor/metatile_material_top.bin"

	.align 1
gMetatileMaterialBottom_Fallarbor::
	.incbin "data/tilesets/secondary/fallarbor/metatile_material_bottom.bin"

	.align 1
gMetatiles_Fortree::
	.incbin "data/tilesets/secondary/fortree/metatiles.bin"

	.align 1
gMetatileAttributes_Fortree::
	.incbin "data/tilesets/secondary/fortree/metatile_attributes.bin"

	.align 1
gMetatileAttributes2_Fortree::
	.incbin "data/tilesets/secondary/fortree/metatile_attributes_2.bin"

	.align 1
gMetatileMaterialTop_Fortree::
	.incbin "data/tilesets/secondary/fortree/metatile_material_top.bin"

	.align 1
gMetatileMaterialBottom_Fortree::
	.incbin "data/tilesets/secondary/fortree/metatile_material_bottom.bin"

	.align 1
gMetatiles_Lilycove::
	.incbin "data/tilesets/secondary/lilycove/metatiles.bin"

	.align 1
gMetatileAttributes_Lilycove::
	.incbin "data/tilesets/secondary/lilycove/metatile_attributes.bin"

	.align 1
gMetatileAttributes2_Lilycove::
	.incbin "data/tilesets/secondary/lilycove/metatile_attributes_2.bin"

	.align 1
gMetatileMaterialTop_Lilycove::
	.incbin "data/tilesets/secondary/lilycove/metatile_material_top.bin"

	.align 1
gMetatileMaterialBottom_Lilycove::
	.incbin "data/tilesets/secondary/lilycove/metatile_material_bottom.bin"

	.align 1
gMetatiles_Mossdeep::
	.incbin "data/tilesets/secondary/mossdeep/metatiles.bin"

	.align 1
gMetatileAttributes_Mossdeep::
	.incbin "data/tilesets/secondary/mossdeep/metatile_attributes.bin"

	.align 1
gMetatileAttributes2_Mossdeep::
	.incbin "data/tilesets/secondary/mossdeep/metatile_attributes_2.bin"

	.align 1
gMetatileMaterialTop_Mossdeep::
	.incbin "data/tilesets/secondary/mossdeep/metatile_material_top.bin"

	.align 1
gMetatileMaterialBottom_Mossdeep::
	.incbin "data/tilesets/secondary/mossdeep/metatile_material_bottom.bin"

	.align 1
gMetatiles_EverGrande::
	.incbin "data/tilesets/secondary/ever_grande/metatiles.bin"

	.align 1
gMetatileAttributes_EverGrande::
	.incbin "data/tilesets/secondary/ever_grande/metatile_attributes.bin"

	.align 1
gMetatileAttributes2_EverGrande::
	.incbin "data/tilesets/secondary/ever_grande/metatile_attributes_2.bin"

	.align 1
gMetatileMaterialTop_EverGrande::
	.incbin "data/tilesets/secondary/ever_grande/metatile_material_top.bin"

	.align 1
gMetatileMaterialBottom_EverGrande::
	.incbin "data/tilesets/secondary/ever_grande/metatile_material_bottom.bin"

	.align 1
gMetatiles_Pacifidlog::
	.incbin "data/tilesets/secondary/pacifidlog/metatiles.bin"

	.align 1
gMetatileAttributes_Pacifidlog::
	.incbin "data/tilesets/secondary/pacifidlog/metatile_attributes.bin"

	.align 1
gMetatileAttributes2_Pacifidlog::
	.incbin "data/tilesets/secondary/pacifidlog/metatile_attributes_2.bin"

	.align 1
gMetatileMaterialTop_Pacifidlog::
	.incbin "data/tilesets/secondary/pacifidlog/metatile_material_top.bin"

	.align 1
gMetatileMaterialBottom_Pacifidlog::
	.incbin "data/tilesets/secondary/pacifidlog/metatile_material_bottom.bin"

	.align 1
gMetatiles_Sootopolis::
	.incbin "data/tilesets/secondary/sootopolis/metatiles.bin"

	.align 1
gMetatileAttributes_Sootopolis::
	.incbin "data/tilesets/secondary/sootopolis/metatile_attributes.bin"

	.align 1
gMetatileAttributes2_Sootopolis::
	.incbin "data/tilesets/secondary/sootopolis/metatile_attributes_2.bin"

	.align 1
gMetatileMaterialTop_Sootopolis::
	.incbin "data/tilesets/secondary/sootopolis/metatile_material_top.bin"

	.align 1
gMetatileMaterialBottom_Sootopolis::
	.incbin "data/tilesets/secondary/sootopolis/metatile_material_bottom.bin"

	.align 1
gMetatiles_BattleFrontierOutsideWest::
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/metatiles.bin"

	.align 1
gMetatileAttributes_BattleFrontierOutsideWest::
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/metatile_attributes.bin"

	.align 1
gMetatileAttributes2_BattleFrontierOutsideWest::
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/metatile_attributes_2.bin"

	.align 1
gMetatileMaterialTop_BattleFrontierOutsideWest::
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/metatile_material_top.bin"

	.align 1
gMetatileMaterialBottom_BattleFrontierOutsideWest::
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/metatile_material_bottom.bin"

	.align 1
gMetatiles_BattleFrontierOutsideEast::
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/metatiles.bin"

	.align 1
gMetatileAttributes_BattleFrontierOutsideEast::
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/metatile_attributes.bin"

	.align 1
gMetatileAttributes2_BattleFrontierOutsideEast::
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/metatile_attributes_2.bin"

	.align 1
gMetatileMaterialTop_BattleFrontierOutsideEast::
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/metatile_material_top.bin"

	.align 1
gMetatileMaterialBottom_BattleFrontierOutsideEast::
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/metatile_material_bottom.bin"

	.align 1
gMetatiles_InsideBuilding::
	.incbin "data/tilesets/primary/building/metatiles.bin"

	.align 1
gMetatileAttributes_InsideBuilding::
	.incbin "data/tilesets/primary/building/metatile_attributes.bin"

	.align 1
gMetatileAttributes2_InsideBuilding::
	.incbin "data/tilesets/primary/building/metatile_attributes_2.bin"

	.align 1
gMetatileMaterialTop_InsideBuilding::
	.incbin "data/tilesets/primary/building/metatile_material_top.bin"

	.align 1
gMetatileMaterialBottom_InsideBuilding::
	.incbin "data/tilesets/primary/building/metatile_material_bottom.bin"

	.align 1
gMetatiles_Shop::
	.incbin "data/tilesets/secondary/shop/metatiles.bin"

	.align 1
gMetatileAttributes_Shop::
	.incbin "data/tilesets/secondary/shop/metatile_attributes.bin"

	.align 1
gMetatileAttributes2_Shop::
	.incbin "data/tilesets/secondary/shop/metatile_attributes_2.bin"

	.align 1
gMetatileMaterialTop_Shop::
	.incbin "data/tilesets/secondary/shop/metatile_material_top.bin"

	.align 1
gMetatileMaterialBottom_Shop::
	.incbin "data/tilesets/secondary/shop/metatile_material_bottom.bin"

	.align 1
gMetatiles_PokemonCenter::
	.incbin "data/tilesets/secondary/pokemon_center/metatiles.bin"

	.align 1
gMetatileAttributes_PokemonCenter::
	.incbin "data/tilesets/secondary/pokemon_center/metatile_attributes.bin"

	.align 1
gMetatileAttributes2_PokemonCenter::
	.incbin "data/tilesets/secondary/pokemon_center/metatile_attributes_2.bin"

	.align 1
gMetatileMaterialTop_PokemonCenter::
	.incbin "data/tilesets/secondary/pokemon_center/metatile_material_top.bin"

	.align 1
gMetatileMaterialBottom_PokemonCenter::
	.incbin "data/tilesets/secondary/pokemon_center/metatile_material_bottom.bin"

	.align 1
gMetatiles_Cave::
	.incbin "data/tilesets/secondary/cave/metatiles.bin"

	.align 1
gMetatileAttributes_Cave::
	.incbin "data/tilesets/secondary/cave/metatile_attributes.bin"

	.align 1
gMetatileAttributes2_Cave::
	.incbin "data/tilesets/secondary/cave/metatile_attributes_2.bin"

	.align 1
gMetatileMaterialTop_Cave::
	.incbin "data/tilesets/secondary/cave/metatile_material_top.bin"

	.align 1
gMetatileMaterialBottom_Cave::
	.incbin "data/tilesets/secondary/cave/metatile_material_bottom.bin"

	.align 1
gMetatiles_PokemonSchool::
	.incbin "data/tilesets/secondary/pokemon_school/metatiles.bin"

	.align 1
gMetatileAttributes_PokemonSchool::
	.incbin "data/tilesets/secondary/pokemon_school/metatile_attributes.bin"

	.align 1
gMetatileAttributes2_PokemonSchool::
	.incbin "data/tilesets/secondary/pokemon_school/metatile_attributes_2.bin"

	.align 1
gMetatileMaterialTop_PokemonSchool::
	.incbin "data/tilesets/secondary/pokemon_school/metatile_material_top.bin"

	.align 1
gMetatileMaterialBottom_PokemonSchool::
	.incbin "data/tilesets/secondary/pokemon_school/metatile_material_bottom.bin"

	.align 1
gMetatiles_PokemonFanClub::
	.incbin "data/tilesets/secondary/pokemon_fan_club/metatiles.bin"

	.align 1
gMetatileAttributes_PokemonFanClub::
	.incbin "data/tilesets/secondary/pokemon_fan_club/metatile_attributes.bin"

	.align 1
gMetatileAttributes2_PokemonFanClub::
	.incbin "data/tilesets/secondary/pokemon_fan_club/metatile_attributes_2.bin"

	.align 1
gMetatileMaterialTop_PokemonFanClub::
	.incbin "data/tilesets/secondary/pokemon_fan_club/metatile_material_top.bin"

	.align 1
gMetatileMaterialBottom_PokemonFanClub::
	.incbin "data/tilesets/secondary/pokemon_fan_club/metatile_material_bottom.bin"

	.align 1
gMetatiles_Unused1::
	.incbin "data/tilesets/secondary/unused_1/metatiles.bin"

	.align 1
gMetatileAttributes_Unused1::
	.incbin "data/tilesets/secondary/unused_1/metatile_attributes.bin"

	.align 1
gMetatileAttributes2_Unused1::
	.incbin "data/tilesets/secondary/unused_1/metatile_attributes_2.bin"

	.align 1
gMetatileMaterialTop_Unused1::
	.incbin "data/tilesets/secondary/unused_1/metatile_material_top.bin"

	.align 1
gMetatileMaterialBottom_Unused1::
	.incbin "data/tilesets/secondary/unused_1/metatile_material_bottom.bin"

	.align 1
gMetatiles_MeteorFalls::
	.incbin "data/tilesets/secondary/meteor_falls/metatiles.bin"

	.align 1
gMetatileAttributes_MeteorFalls::
	.incbin "data/tilesets/secondary/meteor_falls/metatile_attributes.bin"

	.align 1
gMetatileAttributes2_MeteorFalls::
	.incbin "data/tilesets/secondary/meteor_falls/metatile_attributes_2.bin"

	.align 1
gMetatileMaterialTop_MeteorFalls::
	.incbin "data/tilesets/secondary/meteor_falls/metatile_material_top.bin"

	.align 1
gMetatileMaterialBottom_MeteorFalls::
	.incbin "data/tilesets/secondary/meteor_falls/metatile_material_bottom.bin"

	.align 1
gMetatiles_OceanicMuseum::
	.incbin "data/tilesets/secondary/oceanic_museum/metatiles.bin"

	.align 1
gMetatileAttributes_OceanicMuseum::
	.incbin "data/tilesets/secondary/oceanic_museum/metatile_attributes.bin"

	.align 1
gMetatileAttributes2_OceanicMuseum::
	.incbin "data/tilesets/secondary/oceanic_museum/metatile_attributes_2.bin"

	.align 1
gMetatileMaterialTop_OceanicMuseum::
	.incbin "data/tilesets/secondary/oceanic_museum/metatile_material_top.bin"

	.align 1
gMetatileMaterialBottom_OceanicMuseum::
	.incbin "data/tilesets/secondary/oceanic_museum/metatile_material_bottom.bin"

	.align 1
gMetatiles_CableClub::
	.incbin "data/tilesets/secondary/cable_club/metatiles.bin"

	.align 1
gMetatileAttributes_CableClub::
	.incbin "data/tilesets/secondary/cable_club/metatile_attributes.bin"

	.align 1
gMetatileAttributes2_CableClub::
	.incbin "data/tilesets/secondary/cable_club/metatile_attributes_2.bin"

	.align 1
gMetatileMaterialTop_CableClub::
	.incbin "data/tilesets/secondary/cable_club/metatile_material_top.bin"

	.align 1
gMetatileMaterialBottom_CableClub::
	.incbin "data/tilesets/secondary/cable_club/metatile_material_bottom.bin"

	.align 1
gMetatiles_SeashoreHouse::
	.incbin "data/tilesets/secondary/seashore_house/metatiles.bin"

	.align 1
gMetatileAttributes_SeashoreHouse::
	.incbin "data/tilesets/secondary/seashore_house/metatile_attributes.bin"

	.align 1
gMetatileAttributes2_SeashoreHouse::
	.incbin "data/tilesets/secondary/seashore_house/metatile_attributes_2.bin"

	.align 1
gMetatileMaterialTop_SeashoreHouse::
	.incbin "data/tilesets/secondary/seashore_house/metatile_material_top.bin"

	.align 1
gMetatileMaterialBottom_SeashoreHouse::
	.incbin "data/tilesets/secondary/seashore_house/metatile_material_bottom.bin"

	.align 1
gMetatiles_PrettyPetalFlowerShop::
	.incbin "data/tilesets/secondary/pretty_petal_flower_shop/metatiles.bin"

	.align 1
gMetatileAttributes_PrettyPetalFlowerShop::
	.incbin "data/tilesets/secondary/pretty_petal_flower_shop/metatile_attributes.bin"

	.align 1
gMetatileAttributes2_PrettyPetalFlowerShop::
	.incbin "data/tilesets/secondary/pretty_petal_flower_shop/metatile_attributes_2.bin"

	.align 1
gMetatileMaterialTop_PrettyPetalFlowerShop::
	.incbin "data/tilesets/secondary/pretty_petal_flower_shop/metatile_material_top.bin"

	.align 1
gMetatileMaterialBottom_PrettyPetalFlowerShop::
	.incbin "data/tilesets/secondary/pretty_petal_flower_shop/metatile_material_bottom.bin"

	.align 1
gMetatiles_PokemonDayCare::
	.incbin "data/tilesets/secondary/pokemon_day_care/metatiles.bin"

	.align 1
gMetatileAttributes_PokemonDayCare::
	.incbin "data/tilesets/secondary/pokemon_day_care/metatile_attributes.bin"

	.align 1
gMetatileAttributes2_PokemonDayCare::
	.incbin "data/tilesets/secondary/pokemon_day_care/metatile_attributes_2.bin"

	.align 1
gMetatileMaterialTop_PokemonDayCare::
	.incbin "data/tilesets/secondary/pokemon_day_care/metatile_material_top.bin"

	.align 1
gMetatileMaterialBottom_PokemonDayCare::
	.incbin "data/tilesets/secondary/pokemon_day_care/metatile_material_bottom.bin"

	.align 1
gMetatiles_Facility::
	.incbin "data/tilesets/secondary/facility/metatiles.bin"

	.align 1
gMetatileAttributes_Facility::
	.incbin "data/tilesets/secondary/facility/metatile_attributes.bin"

	.align 1
gMetatileAttributes2_Facility::
	.incbin "data/tilesets/secondary/facility/metatile_attributes_2.bin"

	.align 1
gMetatileMaterialTop_Facility::
	.incbin "data/tilesets/secondary/facility/metatile_material_top.bin"

	.align 1
gMetatileMaterialBottom_Facility::
	.incbin "data/tilesets/secondary/facility/metatile_material_bottom.bin"

	.align 1
gMetatiles_BikeShop::
	.incbin "data/tilesets/secondary/bike_shop/metatiles.bin"

	.align 1
gMetatileAttributes_BikeShop::
	.incbin "data/tilesets/secondary/bike_shop/metatile_attributes.bin"

	.align 1
gMetatileAttributes2_BikeShop::
	.incbin "data/tilesets/secondary/bike_shop/metatile_attributes_2.bin"

	.align 1
gMetatileMaterialTop_BikeShop::
	.incbin "data/tilesets/secondary/bike_shop/metatile_material_top.bin"

	.align 1
gMetatileMaterialBottom_BikeShop::
	.incbin "data/tilesets/secondary/bike_shop/metatile_material_bottom.bin"

	.align 1
gMetatiles_RusturfTunnel::
	.incbin "data/tilesets/secondary/rusturf_tunnel/metatiles.bin"

	.align 1
gMetatileAttributes_RusturfTunnel::
	.incbin "data/tilesets/secondary/rusturf_tunnel/metatile_attributes.bin"

	.align 1
gMetatileAttributes2_RusturfTunnel::
	.incbin "data/tilesets/secondary/rusturf_tunnel/metatile_attributes_2.bin"

	.align 1
gMetatileMaterialTop_RusturfTunnel::
	.incbin "data/tilesets/secondary/rusturf_tunnel/metatile_material_top.bin"

	.align 1
gMetatileMaterialBottom_RusturfTunnel::
	.incbin "data/tilesets/secondary/rusturf_tunnel/metatile_material_bottom.bin"

	.align 1
gMetatiles_SecretBaseSecondary::
	.incbin "data/tilesets/secondary/secret_base/metatiles.bin"

	.align 1
gMetatileAttributes_SecretBaseSecondary::
	.incbin "data/tilesets/secondary/secret_base/metatile_attributes.bin"

	.align 1
gMetatileAttributes2_SecretBaseSecondary::
	.incbin "data/tilesets/secondary/secret_base/metatile_attributes_2.bin"

	.align 1
gMetatileMaterialTop_SecretBaseSecondary::
	.incbin "data/tilesets/secondary/secret_base/metatile_material_top.bin"

	.align 1
gMetatileMaterialBottom_SecretBaseSecondary::
	.incbin "data/tilesets/secondary/secret_base/metatile_material_bottom.bin"

	.align 1
gMetatiles_InsideOfTruck::
	.incbin "data/tilesets/secondary/inside_of_truck/metatiles.bin"

	.align 1
gMetatileAttributes_InsideOfTruck::
	.incbin "data/tilesets/secondary/inside_of_truck/metatile_attributes.bin"

	.align 1
gMetatileAttributes2_InsideOfTruck::
	.incbin "data/tilesets/secondary/inside_of_truck/metatile_attributes_2.bin"

	.align 1
gMetatileMaterialTop_InsideOfTruck::
	.incbin "data/tilesets/secondary/inside_of_truck/metatile_material_top.bin"

	.align 1
gMetatileMaterialBottom_InsideOfTruck::
	.incbin "data/tilesets/secondary/inside_of_truck/metatile_material_bottom.bin"

	.align 1
gMetatiles_Contest::
	.incbin "data/tilesets/secondary/contest/metatiles.bin"

	.align 1
gMetatileAttributes_Contest::
	.incbin "data/tilesets/secondary/contest/metatile_attributes.bin"

	.align 1
gMetatileAttributes2_Contest::
	.incbin "data/tilesets/secondary/contest/metatile_attributes_2.bin"

	.align 1
gMetatileMaterialTop_Contest::
	.incbin "data/tilesets/secondary/contest/metatile_material_top.bin"

	.align 1
gMetatileMaterialBottom_Contest::
	.incbin "data/tilesets/secondary/contest/metatile_material_bottom.bin"

	.align 1
gMetatiles_LilycoveMuseum::
	.incbin "data/tilesets/secondary/lilycove_museum/metatiles.bin"

	.align 1
gMetatileAttributes_LilycoveMuseum::
	.incbin "data/tilesets/secondary/lilycove_museum/metatile_attributes.bin"

	.align 1
gMetatileAttributes2_LilycoveMuseum::
	.incbin "data/tilesets/secondary/lilycove_museum/metatile_attributes_2.bin"

	.align 1
gMetatileMaterialTop_LilycoveMuseum::
	.incbin "data/tilesets/secondary/lilycove_museum/metatile_material_top.bin"

	.align 1
gMetatileMaterialBottom_LilycoveMuseum::
	.incbin "data/tilesets/secondary/lilycove_museum/metatile_material_bottom.bin"

	.align 1
gMetatiles_BrendansMaysHouse::
	.incbin "data/tilesets/secondary/brendans_mays_house/metatiles.bin"

	.align 1
gMetatileAttributes_BrendansMaysHouse::
	.incbin "data/tilesets/secondary/brendans_mays_house/metatile_attributes.bin"

	.align 1
gMetatileAttributes2_BrendansMaysHouse::
	.incbin "data/tilesets/secondary/brendans_mays_house/metatile_attributes_2.bin"

	.align 1
gMetatileMaterialTop_BrendansMaysHouse::
	.incbin "data/tilesets/secondary/brendans_mays_house/metatile_material_top.bin"

	.align 1
gMetatileMaterialBottom_BrendansMaysHouse::
	.incbin "data/tilesets/secondary/brendans_mays_house/metatile_material_bottom.bin"

	.align 1
gMetatiles_Lab::
	.incbin "data/tilesets/secondary/lab/metatiles.bin"

	.align 1
gMetatileAttributes_Lab::
	.incbin "data/tilesets/secondary/lab/metatile_attributes.bin"

	.align 1
gMetatileAttributes2_Lab::
	.incbin "data/tilesets/secondary/lab/metatile_attributes_2.bin"

	.align 1
gMetatileMaterialTop_Lab::
	.incbin "data/tilesets/secondary/lab/metatile_material_top.bin"

	.align 1
gMetatileMaterialBottom_Lab::
	.incbin "data/tilesets/secondary/lab/metatile_material_bottom.bin"

	.align 1
gMetatiles_Underwater::
	.incbin "data/tilesets/secondary/underwater/metatiles.bin"

	.align 1
gMetatileAttributes_Underwater::
	.incbin "data/tilesets/secondary/underwater/metatile_attributes.bin"

	.align 1
gMetatileAttributes2_Underwater::
	.incbin "data/tilesets/secondary/underwater/metatile_attributes_2.bin"

	.align 1
gMetatileMaterialTop_Underwater::
	.incbin "data/tilesets/secondary/underwater/metatile_material_top.bin"

	.align 1
gMetatileMaterialBottom_Underwater::
	.incbin "data/tilesets/secondary/underwater/metatile_material_bottom.bin"

	.align 1
gMetatiles_GenericBuilding::
	.incbin "data/tilesets/secondary/generic_building/metatiles.bin"

	.align 1
gMetatileAttributes_GenericBuilding::
	.incbin "data/tilesets/secondary/generic_building/metatile_attributes.bin"

	.align 1
gMetatileAttributes2_GenericBuilding::
	.incbin "data/tilesets/secondary/generic_building/metatile_attributes_2.bin"

	.align 1
gMetatileMaterialTop_GenericBuilding::
	.incbin "data/tilesets/secondary/generic_building/metatile_material_top.bin"

	.align 1
gMetatileMaterialBottom_GenericBuilding::
	.incbin "data/tilesets/secondary/generic_building/metatile_material_bottom.bin"

	.align 1
gMetatiles_MauvilleGameCorner::
	.incbin "data/tilesets/secondary/mauville_game_corner/metatiles.bin"

	.align 1
gMetatileAttributes_MauvilleGameCorner::
	.incbin "data/tilesets/secondary/mauville_game_corner/metatile_attributes.bin"

	.align 1
gMetatileAttributes2_MauvilleGameCorner::
	.incbin "data/tilesets/secondary/mauville_game_corner/metatile_attributes_2.bin"

	.align 1
gMetatileMaterialTop_MauvilleGameCorner::
	.incbin "data/tilesets/secondary/mauville_game_corner/metatile_material_top.bin"

	.align 1
gMetatileMaterialBottom_MauvilleGameCorner::
	.incbin "data/tilesets/secondary/mauville_game_corner/metatile_material_bottom.bin"

	.align 1
gMetatiles_Unused2::
	.incbin "data/tilesets/secondary/unused_2/metatiles.bin"

	.align 1
gMetatileAttributes_Unused2::
	.incbin "data/tilesets/secondary/unused_2/metatile_attributes.bin"

	.align 1
gMetatileAttributes2_Unused2::
	.incbin "data/tilesets/secondary/unused_2/metatile_attributes_2.bin"

	.align 1
gMetatileMaterialTop_Unused2::
	.incbin "data/tilesets/secondary/unused_2/metatile_material_top.bin"

	.align 1
gMetatileMaterialBottom_Unused2::
	.incbin "data/tilesets/secondary/unused_2/metatile_material_bottom.bin"

	.align 1
gMetatiles_RustboroGym::
	.incbin "data/tilesets/secondary/rustboro_gym/metatiles.bin"

	.align 1
gMetatileAttributes_RustboroGym::
	.incbin "data/tilesets/secondary/rustboro_gym/metatile_attributes.bin"

	.align 1
gMetatileAttributes2_RustboroGym::
	.incbin "data/tilesets/secondary/rustboro_gym/metatile_attributes_2.bin"

	.align 1
gMetatileMaterialTop_RustboroGym::
	.incbin "data/tilesets/secondary/rustboro_gym/metatile_material_top.bin"

	.align 1
gMetatileMaterialBottom_RustboroGym::
	.incbin "data/tilesets/secondary/rustboro_gym/metatile_material_bottom.bin"

	.align 1
gMetatiles_DewfordGym::
	.incbin "data/tilesets/secondary/dewford_gym/metatiles.bin"

	.align 1
gMetatileAttributes_DewfordGym::
	.incbin "data/tilesets/secondary/dewford_gym/metatile_attributes.bin"

	.align 1
gMetatileAttributes2_DewfordGym::
	.incbin "data/tilesets/secondary/dewford_gym/metatile_attributes_2.bin"

	.align 1
gMetatileMaterialTop_DewfordGym::
	.incbin "data/tilesets/secondary/dewford_gym/metatile_material_top.bin"

	.align 1
gMetatileMaterialBottom_DewfordGym::
	.incbin "data/tilesets/secondary/dewford_gym/metatile_material_bottom.bin"

	.align 1
gMetatiles_MauvilleGym::
	.incbin "data/tilesets/secondary/mauville_gym/metatiles.bin"

	.align 1
gMetatileAttributes_MauvilleGym::
	.incbin "data/tilesets/secondary/mauville_gym/metatile_attributes.bin"

	.align 1
gMetatileAttributes2_MauvilleGym::
	.incbin "data/tilesets/secondary/mauville_gym/metatile_attributes_2.bin"

	.align 1
gMetatileMaterialTop_MauvilleGym::
	.incbin "data/tilesets/secondary/mauville_gym/metatile_material_top.bin"

	.align 1
gMetatileMaterialBottom_MauvilleGym::
	.incbin "data/tilesets/secondary/mauville_gym/metatile_material_bottom.bin"

	.align 1
gMetatiles_LavaridgeGym::
	.incbin "data/tilesets/secondary/lavaridge_gym/metatiles.bin"

	.align 1
gMetatileAttributes_LavaridgeGym::
	.incbin "data/tilesets/secondary/lavaridge_gym/metatile_attributes.bin"

	.align 1
gMetatileAttributes2_LavaridgeGym::
	.incbin "data/tilesets/secondary/lavaridge_gym/metatile_attributes_2.bin"

	.align 1
gMetatileMaterialTop_LavaridgeGym::
	.incbin "data/tilesets/secondary/lavaridge_gym/metatile_material_top.bin"

	.align 1
gMetatileMaterialBottom_LavaridgeGym::
	.incbin "data/tilesets/secondary/lavaridge_gym/metatile_material_bottom.bin"

	.align 1
gMetatiles_PetalburgGym::
	.incbin "data/tilesets/secondary/petalburg_gym/metatiles.bin"

	.align 1
gMetatileAttributes_PetalburgGym::
	.incbin "data/tilesets/secondary/petalburg_gym/metatile_attributes.bin"

	.align 1
gMetatileAttributes2_PetalburgGym::
	.incbin "data/tilesets/secondary/petalburg_gym/metatile_attributes_2.bin"

	.align 1
gMetatileMaterialTop_PetalburgGym::
	.incbin "data/tilesets/secondary/petalburg_gym/metatile_material_top.bin"

	.align 1
gMetatileMaterialBottom_PetalburgGym::
	.incbin "data/tilesets/secondary/petalburg_gym/metatile_material_bottom.bin"

	.align 1
gMetatiles_FortreeGym::
	.incbin "data/tilesets/secondary/fortree_gym/metatiles.bin"

	.align 1
gMetatileAttributes_FortreeGym::
	.incbin "data/tilesets/secondary/fortree_gym/metatile_attributes.bin"

	.align 1
gMetatileAttributes2_FortreeGym::
	.incbin "data/tilesets/secondary/fortree_gym/metatile_attributes_2.bin"

	.align 1
gMetatileMaterialTop_FortreeGym::
	.incbin "data/tilesets/secondary/fortree_gym/metatile_material_top.bin"

	.align 1
gMetatileMaterialBottom_FortreeGym::
	.incbin "data/tilesets/secondary/fortree_gym/metatile_material_bottom.bin"

	.align 1
gMetatiles_MossdeepGym::
	.incbin "data/tilesets/secondary/mossdeep_gym/metatiles.bin"

	.align 1
gMetatileAttributes_MossdeepGym::
	.incbin "data/tilesets/secondary/mossdeep_gym/metatile_attributes.bin"

	.align 1
gMetatileAttributes2_MossdeepGym::
	.incbin "data/tilesets/secondary/mossdeep_gym/metatile_attributes_2.bin"

	.align 1
gMetatileMaterialTop_MossdeepGym::
	.incbin "data/tilesets/secondary/mossdeep_gym/metatile_material_top.bin"

	.align 1
gMetatileMaterialBottom_MossdeepGym::
	.incbin "data/tilesets/secondary/mossdeep_gym/metatile_material_bottom.bin"

	.align 1
gMetatiles_SootopolisGym::
	.incbin "data/tilesets/secondary/sootopolis_gym/metatiles.bin"

	.align 1
gMetatileAttributes_SootopolisGym::
	.incbin "data/tilesets/secondary/sootopolis_gym/metatile_attributes.bin"

	.align 1
gMetatileAttributes2_SootopolisGym::
	.incbin "data/tilesets/secondary/sootopolis_gym/metatile_attributes_2.bin"

	.align 1
gMetatileMaterialTop_SootopolisGym::
	.incbin "data/tilesets/secondary/sootopolis_gym/metatile_material_top.bin"

	.align 1
gMetatileMaterialBottom_SootopolisGym::
	.incbin "data/tilesets/secondary/sootopolis_gym/metatile_material_bottom.bin"

	.align 1
gMetatiles_TrickHousePuzzle::
	.incbin "data/tilesets/secondary/trick_house_puzzle/metatiles.bin"

	.align 1
gMetatileAttributes_TrickHousePuzzle::
	.incbin "data/tilesets/secondary/trick_house_puzzle/metatile_attributes.bin"

	.align 1
gMetatileAttributes2_TrickHousePuzzle::
	.incbin "data/tilesets/secondary/trick_house_puzzle/metatile_attributes_2.bin"

	.align 1
gMetatileMaterialTop_TrickHousePuzzle::
	.incbin "data/tilesets/secondary/trick_house_puzzle/metatile_material_top.bin"

	.align 1
gMetatileMaterialBottom_TrickHousePuzzle::
	.incbin "data/tilesets/secondary/trick_house_puzzle/metatile_material_bottom.bin"

	.align 1
gMetatiles_InsideShip::
	.incbin "data/tilesets/secondary/inside_ship/metatiles.bin"

	.align 1
gMetatileAttributes_InsideShip::
	.incbin "data/tilesets/secondary/inside_ship/metatile_attributes.bin"

	.align 1
gMetatileAttributes2_InsideShip::
	.incbin "data/tilesets/secondary/inside_ship/metatile_attributes_2.bin"

	.align 1
gMetatileMaterialTop_InsideShip::
	.incbin "data/tilesets/secondary/inside_ship/metatile_material_top.bin"

	.align 1
gMetatileMaterialBottom_InsideShip::
	.incbin "data/tilesets/secondary/inside_ship/metatile_material_bottom.bin"

	.align 1
gMetatiles_SecretBasePrimary::
	.incbin "data/tilesets/primary/secret_base/metatiles.bin"

	.align 1
gMetatileAttributes_SecretBasePrimary::
	.incbin "data/tilesets/primary/secret_base/metatile_attributes.bin"

	.align 1
gMetatileAttributes2_SecretBasePrimary::
	.incbin "data/tilesets/primary/secret_base/metatile_attributes_2.bin"

	.align 1
gMetatileMaterialTop_SecretBasePrimary::
	.incbin "data/tilesets/primary/secret_base/metatile_material_top.bin"

	.align 1
gMetatileMaterialBottom_SecretBasePrimary::
	.incbin "data/tilesets/primary/secret_base/metatile_material_bottom.bin"

	.align 1
gMetatiles_EliteFour::
	.incbin "data/tilesets/secondary/elite_four/metatiles.bin"

	.align 1
gMetatileAttributes_EliteFour::
	.incbin "data/tilesets/secondary/elite_four/metatile_attributes.bin"

	.align 1
gMetatileAttributes2_EliteFour::
	.incbin "data/tilesets/secondary/elite_four/metatile_attributes_2.bin"

	.align 1
gMetatileMaterialTop_EliteFour::
	.incbin "data/tilesets/secondary/elite_four/metatile_material_top.bin"

	.align 1
gMetatileMaterialBottom_EliteFour::
	.incbin "data/tilesets/secondary/elite_four/metatile_material_bottom.bin"

	.align 1
gMetatiles_BattleFrontier::
	.incbin "data/tilesets/secondary/battle_frontier/metatiles.bin"

	.align 1
gMetatileAttributes_BattleFrontier::
	.incbin "data/tilesets/secondary/battle_frontier/metatile_attributes.bin"

	.align 1
gMetatileAttributes2_BattleFrontier::
	.incbin "data/tilesets/secondary/battle_frontier/metatile_attributes_2.bin"

	.align 1
gMetatileMaterialTop_BattleFrontier::
	.incbin "data/tilesets/secondary/battle_frontier/metatile_material_top.bin"

	.align 1
gMetatileMaterialBottom_BattleFrontier::
	.incbin "data/tilesets/secondary/battle_frontier/metatile_material_bottom.bin"

	.align 1
gMetatiles_BattlePalace::
	.incbin "data/tilesets/secondary/battle_palace/metatiles.bin"

	.align 1
gMetatileAttributes_BattlePalace::
	.incbin "data/tilesets/secondary/battle_palace/metatile_attributes.bin"

	.align 1
gMetatileAttributes2_BattlePalace::
	.incbin "data/tilesets/secondary/battle_palace/metatile_attributes_2.bin"

	.align 1
gMetatileMaterialTop_BattlePalace::
	.incbin "data/tilesets/secondary/battle_palace/metatile_material_top.bin"

	.align 1
gMetatileMaterialBottom_BattlePalace::
	.incbin "data/tilesets/secondary/battle_palace/metatile_material_bottom.bin"

	.align 1
gMetatiles_BattleDome::
	.incbin "data/tilesets/secondary/battle_dome/metatiles.bin"

	.align 1
gMetatileAttributes_BattleDome::
	.incbin "data/tilesets/secondary/battle_dome/metatile_attributes.bin"

	.align 1
gMetatileAttributes2_BattleDome::
	.incbin "data/tilesets/secondary/battle_dome/metatile_attributes_2.bin"

	.align 1
gMetatileMaterialTop_BattleDome::
	.incbin "data/tilesets/secondary/battle_dome/metatile_material_top.bin"

	.align 1
gMetatileMaterialBottom_BattleDome::
	.incbin "data/tilesets/secondary/battle_dome/metatile_material_bottom.bin"

	.align 1
gMetatiles_BattleFactory::
	.incbin "data/tilesets/secondary/battle_factory/metatiles.bin"

	.align 1
gMetatileAttributes_BattleFactory::
	.incbin "data/tilesets/secondary/battle_factory/metatile_attributes.bin"

	.align 1
gMetatileAttributes2_BattleFactory::
	.incbin "data/tilesets/secondary/battle_factory/metatile_attributes_2.bin"

	.align 1
gMetatileMaterialTop_BattleFactory::
	.incbin "data/tilesets/secondary/battle_factory/metatile_material_top.bin"

	.align 1
gMetatileMaterialBottom_BattleFactory::
	.incbin "data/tilesets/secondary/battle_factory/metatile_material_bottom.bin"

	.align 1
gMetatiles_BattlePike::
	.incbin "data/tilesets/secondary/battle_pike/metatiles.bin"

	.align 1
gMetatileAttributes_BattlePike::
	.incbin "data/tilesets/secondary/battle_pike/metatile_attributes.bin"

	.align 1
gMetatileAttributes2_BattlePike::
	.incbin "data/tilesets/secondary/battle_pike/metatile_attributes_2.bin"

	.align 1
gMetatileMaterialTop_BattlePike::
	.incbin "data/tilesets/secondary/battle_pike/metatile_material_top.bin"

	.align 1
gMetatileMaterialBottom_BattlePike::
	.incbin "data/tilesets/secondary/battle_pike/metatile_material_bottom.bin"

	.align 1
gMetatiles_BattleArena::
	.incbin "data/tilesets/secondary/battle_arena/metatiles.bin"

	.align 1
gMetatileAttributes_BattleArena::
	.incbin "data/tilesets/secondary/battle_arena/metatile_attributes.bin"

	.align 1
gMetatileAttributes2_BattleArena::
	.incbin "data/tilesets/secondary/battle_arena/metatile_attributes_2.bin"

	.align 1
gMetatileMaterialTop_BattleArena::
	.incbin "data/tilesets/secondary/battle_arena/metatile_material_top.bin"

	.align 1
gMetatileMaterialBottom_BattleArena::
	.incbin "data/tilesets/secondary/battle_arena/metatile_material_bottom.bin"

	.align 1
gMetatiles_BattlePyramid::
	.incbin "data/tilesets/secondary/battle_pyramid/metatiles.bin"

	.align 1
gMetatileAttributes_BattlePyramid::
	.incbin "data/tilesets/secondary/battle_pyramid/metatile_attributes.bin"

	.align 1
gMetatileAttributes2_BattlePyramid::
	.incbin "data/tilesets/secondary/battle_pyramid/metatile_attributes_2.bin"

	.align 1
gMetatileMaterialTop_BattlePyramid::
	.incbin "data/tilesets/secondary/battle_pyramid/metatile_material_top.bin"

	.align 1
gMetatileMaterialBottom_BattlePyramid::
	.incbin "data/tilesets/secondary/battle_pyramid/metatile_material_bottom.bin"

	.align 1
gMetatiles_MirageTower::
	.incbin "data/tilesets/secondary/mirage_tower/metatiles.bin"

	.align 1
gMetatileAttributes_MirageTower::
	.incbin "data/tilesets/secondary/mirage_tower/metatile_attributes.bin"

	.align 1
gMetatileAttributes2_MirageTower::
	.incbin "data/tilesets/secondary/mirage_tower/metatile_attributes_2.bin"

	.align 1
gMetatileMaterialTop_MirageTower::
	.incbin "data/tilesets/secondary/mirage_tower/metatile_material_top.bin"

	.align 1
gMetatileMaterialBottom_MirageTower::
	.incbin "data/tilesets/secondary/mirage_tower/metatile_material_bottom.bin"

	.align 1
gMetatiles_MossdeepGameCorner::
	.incbin "data/tilesets/secondary/mossdeep_game_corner/metatiles.bin"

	.align 1
gMetatileAttributes_MossdeepGameCorner::
	.incbin "data/tilesets/secondary/mossdeep_game_corner/metatile_attributes.bin"

	.align 1
gMetatileAttributes2_MossdeepGameCorner::
	.incbin "data/tilesets/secondary/mossdeep_game_corner/metatile_attributes_2.bin"

	.align 1
gMetatileMaterialTop_MossdeepGameCorner::
	.incbin "data/tilesets/secondary/mossdeep_game_corner/metatile_material_top.bin"

	.align 1
gMetatileMaterialBottom_MossdeepGameCorner::
	.incbin "data/tilesets/secondary/mossdeep_game_corner/metatile_material_bottom.bin"

	.align 1
gMetatiles_IslandHarbor::
	.incbin "data/tilesets/secondary/island_harbor/metatiles.bin"

	.align 1
gMetatileAttributes_IslandHarbor::
	.incbin "data/tilesets/secondary/island_harbor/metatile_attributes.bin"

	.align 1
gMetatileAttributes2_IslandHarbor::
	.incbin "data/tilesets/secondary/island_harbor/metatile_attributes_2.bin"

	.align 1
gMetatileMaterialTop_IslandHarbor::
	.incbin "data/tilesets/secondary/island_harbor/metatile_material_top.bin"

	.align 1
gMetatileMaterialBottom_IslandHarbor::
	.incbin "data/tilesets/secondary/island_harbor/metatile_material_bottom.bin"

	.align 1
gMetatiles_TrainerHill::
	.incbin "data/tilesets/secondary/trainer_hill/metatiles.bin"

	.align 1
gMetatileAttributes_TrainerHill::
	.incbin "data/tilesets/secondary/trainer_hill/metatile_attributes.bin"

	.align 1
gMetatileAttributes2_TrainerHill::
	.incbin "data/tilesets/secondary/trainer_hill/metatile_attributes_2.bin"

	.align 1
gMetatileMaterialTop_TrainerHill::
	.incbin "data/tilesets/secondary/trainer_hill/metatile_material_top.bin"

	.align 1
gMetatileMaterialBottom_TrainerHill::
	.incbin "data/tilesets/secondary/trainer_hill/metatile_material_bottom.bin"

	.align 1
gMetatiles_NavelRock::
	.incbin "data/tilesets/secondary/navel_rock/metatiles.bin"

	.align 1
gMetatileAttributes_NavelRock::
	.incbin "data/tilesets/secondary/navel_rock/metatile_attributes.bin"

	.align 1
gMetatileAttributes2_NavelRock::
	.incbin "data/tilesets/secondary/navel_rock/metatile_attributes_2.bin"

	.align 1
gMetatileMaterialTop_NavelRock::
	.incbin "data/tilesets/secondary/navel_rock/metatile_material_top.bin"

	.align 1
gMetatileMaterialBottom_NavelRock::
	.incbin "data/tilesets/secondary/navel_rock/metatile_material_bottom.bin"

	.align 1
gMetatiles_BattleFrontierRankingHall::
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/metatiles.bin"

	.align 1
gMetatileAttributes_BattleFrontierRankingHall::
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/metatile_attributes.bin"

	.align 1
gMetatileAttributes2_BattleFrontierRankingHall::
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/metatile_attributes_2.bin"

	.align 1
gMetatileMaterialTop_BattleFrontierRankingHall::
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/metatile_material_top.bin"

	.align 1
gMetatileMaterialBottom_BattleFrontierRankingHall::
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/metatile_material_bottom.bin"

	.align 1
gMetatiles_BattleTent::
	.incbin "data/tilesets/secondary/battle_tent/metatiles.bin"

	.align 1
gMetatileAttributes_BattleTent::
	.incbin "data/tilesets/secondary/battle_tent/metatile_attributes.bin"

	.align 1
gMetatileAttributes2_BattleTent::
	.incbin "data/tilesets/secondary/battle_tent/metatile_attributes_2.bin"

	.align 1
gMetatileMaterialTop_BattleTent::
	.incbin "data/tilesets/secondary/battle_tent/metatile_material_top.bin"

	.align 1
gMetatileMaterialBottom_BattleTent::
	.incbin "data/tilesets/secondary/battle_tent/metatile_material_bottom.bin"

	.align 1
gMetatiles_MysteryEventsHouse::
	.incbin "data/tilesets/secondary/mystery_events_house/metatiles.bin"

	.align 1
gMetatileAttributes_MysteryEventsHouse::
	.incbin "data/tilesets/secondary/mystery_events_house/metatile_attributes.bin"

	.align 1
gMetatileAttributes2_MysteryEventsHouse::
	.incbin "data/tilesets/secondary/mystery_events_house/metatile_attributes_2.bin"

	.align 1
gMetatileMaterialTop_MysteryEventsHouse::
	.incbin "data/tilesets/secondary/mystery_events_house/metatile_material_top.bin"

	.align 1
gMetatileMaterialBottom_MysteryEventsHouse::
	.incbin "data/tilesets/secondary/mystery_events_house/metatile_material_bottom.bin"

	.align 1
gMetatiles_UnionRoom::
	.incbin "data/tilesets/secondary/union_room/metatiles.bin"

	.align 1
gMetatileAttributes_UnionRoom::
	.incbin "data/tilesets/secondary/union_room/metatile_attributes.bin"

	.align 1
gMetatileAttributes2_UnionRoom::
	.incbin "data/tilesets/secondary/union_room/metatile_attributes_2.bin"

	.align 1
gMetatileMaterialTop_UnionRoom::
	.incbin "data/tilesets/secondary/union_room/metatile_material_top.bin"

	.align 1
gMetatileMaterialBottom_UnionRoom::
	.incbin "data/tilesets/secondary/union_room/metatile_material_bottom.bin"

	.align 1
gMetatiles_Plains::
	.incbin "data/tilesets/primary/plains/metatiles.bin"

	.align 1
gMetatileAttributes_Plains::
	.incbin "data/tilesets/primary/plains/metatile_attributes.bin"
	
	.align 1
gMetatileAttributes2_Plains::
	.incbin "data/tilesets/primary/plains/metatile_attributes_2.bin"

	.align 1
gMetatileMaterialTop_Plains::
	.incbin "data/tilesets/primary/plains/metatile_material_top.bin"
	
	.align 1
gMetatileMaterialBottom_Plains::
	.incbin "data/tilesets/primary/plains/metatile_material_bottom.bin"
